spring:
  application:
    name: pokedex
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
jwt:
  secret: meusegredo_pokedex
  expiration: 100000
app:
  pokemon:
    url: 'https://pokeapi.co/api/v2/'
  cors:
    allowedOrigins: 'http://localhost:4200'
